package com.helpmefrog.game;

public class Constants {
    /*
        ESTA CLASE PERMITIRÁ LA CONVERSIÓN DE METROS A PIXELES, YA QUE SCENE2D TRABAJA CON PIXELES
        Y BOX2D TRABAJA CON METROS, ENTONCES PARA EVITAR PROBLEMAS CON LAS MEDIDAS SE HA CREADO ESTA
        CLASE :D

        EN DONDE 1 METRO EQUIVALE A 90 PIXELES
     */

    public static final float PIXELS_IN_METER = 90f;

}
